### PR TITLE
fix: better Register screen and movie list

### LINKED ISSUE #88: Registration screen improvements and fixes
As per [feedback from Alan](https://docs.google.com/document/d/1NcUjHBQ94PhQi1hnqfw27JayTPzqllf1DnTTzmmB2J0/edit#) + #87 + #78 

## Scope

Form:
- change prompt text to "Verifying you and your role in individual films is key. This registry helps the film industry ensure only the true rights holders make claims and make new films available for global distribution."
- rename Person field to "Legal Name of Person or Company"
- add "Type of Role or Company" selectbox with [Production, Sales, Distribution, Financing, Public Institution, Other] values
- rename Email field to "Contact e-mail"

Movie list:
- for each of the movies show the RH's job in this movie (see `getPersonCredit` API) (#78)
- make sure each movie is shown only once (fixes #87)

## Roles 

gardener: @troggy + @Right2Rebel 50 DAI
worker: @troggy
reviewer: [reviewer]

### PR DESCRIPTION
**Pull request by troggy**
Please remember the [Contributing Guidelines](https://WhiteRabbitTheWorldIsYours/dashboard/blob/master/CONTRIBUTION.md) :heart:

## What does this PR do?

- enhance Register form as per #88 
- group movie credits by movie id and show the list of jobs per person. Don't show the movies where the RH is only an Actor

## Recommendations for testing
`npm link @whiterabbitjs/dashboard-common` in `frontend`

## Links to relevant issues or information
Closes #88

### CODE REVIEW

File: frontend/src/containers/components/MovieListWithRevenue.tsx [hunk 1]
```diff
@@ -29,9 +31,19 @@ const vaguelyRangeify = (value: number | string) => {
   return '$50,000+';
 };
 
+const renderJob = (movieOrCredit: MovieOrCredit) => {
+  const movie = movieOrCredit as TMDBMovieWithCredits;
+  return movie.jobs && (
+  <div style={{ fontSize: '0.9em', opacity: 0.8 }}>
+    Roles:
```
Comment (Clearwood) [inline frontend/src/containers/components/MovieListWithRevenue.tsx:38]: image
Awesome work, please include a space between roles and jobs
